FROM node:20-alpine

# Create app directory
WORKDIR /app

# Enable corepack and install pnpm
RUN corepack enable && corepack prepare pnpm@latest --activate

# Copy package files and install dependencies
COPY package.json pnpm-lock.yaml* ./
RUN pnpm install

# Copy the rest of the app files
COPY . .

# Expose correct port
EXPOSE 3000  # Change to 5050 or 5173 in other apps

# Use envs passed from Coolify
CMD ["pnpm", "run", "dev"]
